import { DOMAttributes, useState } from "react";
import { Button, Card } from "react-bootstrap";
import { on } from "stream";

interface Tablet {
    tablet_id: number; // Optional ID, as it's likely auto-generated by the database
    name: string; // Name of the tablet
    processor_clock: number; // Clock speed in GHz
    processor_cores: number; // Number of processor cores
    display_size: number; // Size of the display in inches
    resolution_width: number; // Resolution width in pixels
    resolution_height: number; // Resolution height in pixels
    ram: number; // RAM in GB
    description?: string; // Optional description
    price: number; // Price in currency units (e.g., USD, EUR)
    }
interface Props extends React.HTMLAttributes<HTMLDivElement>{
  tablet :Tablet,
  details: boolean
}





export default function Carditem({tablet, onClick, onMouseEnter, onMouseLeave, style, className, details} : Props ) {


const changeColor = () => {
 console.log() 
}


  return (
    <Card style={style} onClick={onClick} onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave} className={"flex-fill mt-4 " + className} >
      <Card.Body>
        <Card.Title>{tablet.name}</Card.Title>
        <Card.Text>
          {tablet.description} <br />
          {tablet.price} Ft
        </Card.Text>
      </Card.Body>

        {details? (
          <Card.Footer>
            <Card.Link href={`/tablets/${tablet.tablet_id}`} >Részletek</Card.Link>
          </Card.Footer>
        ): ( null )}

  </Card>
  )
}