import React, { useEffect, useState } from 'react'
import NavigationBar from './Navbar';
import { Card, Container } from 'react-bootstrap';
import Carditem from './Carditem';


interface Tablet {
  tablet_id: number; // Optional ID, as it's likely auto-generated by the database
  name: string; // Name of the tablet
  processor_clock: number; // Clock speed in GHz
  processor_cores: number; // Number of processor cores
  display_size: number; // Size of the display in inches
  resolution_width: number; // Resolution width in pixels
  resolution_height: number; // Resolution height in pixels
  ram: number; // RAM in GB
  description?: string; // Optional description
  price: number; // Price in currency units (e.g., USD, EUR)
  }

export default function TabletRemove() {

  const [tablets, setTablets] = useState<Tablet[]>([]);
  const [serverError, setServerError] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null)

  const handleClick = () => {
    console.log("click")
  }

  const deleteTablet = async (tabletId:number) => {
    let answer = confirm("Biztosan törölni akarod");
    if (answer){
        try {
            const res:Response = await fetch("http://localhost:3000/tablets/" + tabletId, {
                method: "DELETE",
            })
            if(!res.ok){
                //hibakezelés
            }
            setTablets(tablets.filter((tablet) => tablet.tablet_id !== tabletId))
        } catch (error) {
            
        }
    }
    
}


    useEffect(() => {
        fetch("http://localhost:3000/tablets")
        .then((res) => {
            if(res.status === 404) {
              setServerError("Resource not found 404")
            }
            if (!res.ok) {
              setServerError(`Server responded with status ${res.status}`)
            }
            return res.json();
        })
        .then((data) => {
          setTablets(data)
          setLoading(false)
        })
        .catch((error) => {
          setError(error.message)
          setLoading(false)
        })
    })

  if (loading) {
    return <p>Loading...</p>;
  }

  if (error) {
    return <p>Error: {error}</p>
  }

  return (
    <div>
    <NavigationBar/>
    <h2>Tabletek törlése</h2>
        <div className="container">
      <div className="row">
        {tablets.map(tablet => (
          <div key={tablet.tablet_id} className="col-md-3 d-flex">
            <Carditem tablet={tablet} details={false} style={{cursor: "pointer"}} 
            onMouseEnter={(e) => {
                e.currentTarget.className += " bg-danger text-light" 
            }}
            onMouseLeave={(e) => {
                e.currentTarget.classList.remove("bg-danger")
                e.currentTarget.classList.remove("text-light")
            }}
            
            onClick={() => {
                deleteTablet(tablet.tablet_id)
            }}/>
          </div>
        ))}
      </div>
    </div>
    </div>
  )
}
