import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router';
import NavigationBar from './Navbar';

interface Tablet {
    tablet_id: number; // Optional ID, as it's likely auto-generated by the database
    name: string; // Name of the tablet
    processor_clock: number; // Clock speed in GHz
    processor_cores: number; // Number of processor cores
    display_size: number; // Size of the display in inches
    resolution_width: number; // Resolution width in pixels
    resolution_height: number; // Resolution height in pixels
    ram: number; // RAM in GB
    description?: string; // Optional description
    price: number; // Price in currency units (e.g., USD, EUR)
  }

export default function TabletDetails() {

    const [tablet, setTablet] = useState<Tablet>();
    const [serverError, setServerError] = useState("");
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null)

    const {tabletId} = useParams<{tabletId : string}>()

    useEffect(() => {
        fetch(`http://localhost:3000/tablets/${tabletId}`)
        .then((res) => {
            if(res.status === 404) {
              setServerError("Resource not found 404")
            }
            if (!res.ok) {
              setServerError(`Server responded with status ${res.status}`)
            }
            return res.json();
        })
        .then((data) => {
          setTablet(data)
          setLoading(false)
        })
        .catch((error) => {
          setError(error.message)
          setLoading(false)
        })
    })

  if (loading) {
    return <p>Loading...</p>
  }

  if (error) {
    return <p>Error: {error}</p>
  }

  return (
    <>
    <NavigationBar/>
    <h2>{tablet?.name}</h2>
    <div className='center'>
        {tablet? (
            <div>
                - Processzor órajel: {tablet.processor_clock} GHz <br />
                - Processzormagok száma {tablet.processor_cores} magos <br />
                - Kijelző mérete: {tablet.display_size}" <br />
                - Kijelző felbontás: {tablet.resolution_width} X {tablet.resolution_height} <br />
                - RAM mérete: {tablet.ram} GB <br />
                - Ár: {tablet.price}
            </div>
        ) : (
            <p>No tablet avalible</p>
        )}
    </div>
    </>
  )
}
